v04

diff --git a/.github/workflows/program_builder.yml b/.github/workflows/program_builder.yml
--- a/.github/workflows/program_builder.yml
+++ b/.github/workflows/program_builder.yml
@@ -6,7 +6,7 @@
 #    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/06/12 11:04:11 by umeneses          #+#    #+#              #
-#    Updated: 2024/07/15 12:58:57 by umeneses         ###   ########.fr        #
+#    Updated: 2024/07/15 13:07:26 by umeneses         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -43,24 +43,24 @@ jobs:
       - name: Building Program with MiniShell Makefile
         run: make
       
-      - name: Setup Aptitude
+      - name: Install Aptitude
         run: sudo apt-get update && sudo apt install aptitude -y
       
-      - name: Setup Valgrind
+      - name: Install Valgrind
         run: sudo aptitude install -y valgrind
       
-      - name: Running Valgrind
+      - name: Run Valgrind
         id: valgrind_check
         run: |
           valgrind --track-origins=yes --leak-check=full --suppressions=./readline.sup -q ./minishell || true
+          echo "::set-output name=exit_code::$?"
       
       - name: Check Valgrind Output
         run: |
-          echo "${{ steps.valgrind_check.outputs.stdout }}" | grep -q "ERROR SUMMARY: 0 errors from 0 contexts" && echo "Valgrind check passed" || echo "Valgrind check failed"
+          echo "${{ steps.valgrind_check.outputs.exit_code }}" | grep -q "ERROR SUMMARY: 0 errors from 0 contexts" && echo "Valgrind check passed" || echo "Valgrind check failed"
       
-      - name: Check Valgrind Output
-        run: |
-          echo "VALGRIND_EXIT_CODE=$?" >> $GITHUB_ENV
+      - name: Set Valgrind Exit Code
+        run: echo "VALGRIND_EXIT_CODE=${{ steps.valgrind_check.outputs.exit_code }}" >> $GITHUB_ENV
       
       - name: Fail Job if Memory Leaks Detected
         run: |
