fixing identation

diff --git a/.github/workflows/program_builder.yml b/.github/workflows/program_builder.yml
--- a/.github/workflows/program_builder.yml
+++ b/.github/workflows/program_builder.yml
@@ -6,7 +6,7 @@
 #    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/06/12 11:04:11 by umeneses          #+#    #+#              #
-#    Updated: 2024/07/15 12:57:42 by umeneses         ###   ########.fr        #
+#    Updated: 2024/07/15 12:58:57 by umeneses         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -52,11 +52,11 @@ jobs:
       - name: Running Valgrind
         id: valgrind_check
         run: |
-        valgrind --track-origins=yes --leak-check=full --suppressions=./readline.sup -q ./minishell || true
+          valgrind --track-origins=yes --leak-check=full --suppressions=./readline.sup -q ./minishell || true
       
       - name: Check Valgrind Output
         run: |
-        echo "${{ steps.valgrind_check.outputs.stdout }}" | grep -q "ERROR SUMMARY: 0 errors from 0 contexts" && echo "Valgrind check passed" || echo "Valgrind check failed"
+          echo "${{ steps.valgrind_check.outputs.stdout }}" | grep -q "ERROR SUMMARY: 0 errors from 0 contexts" && echo "Valgrind check passed" || echo "Valgrind check failed"
       
       - name: Check Valgrind Output
         run: |
